### ISSUE TITLE
点删除的时候有时候ajax不起作用，文章还在，然后再点删除的时候，ajax就会报错404

### ISSUE THREAD

**Issue by witcan** [ChrisZou/geekweibo#4]
![image](https://user-images.githubusercontent.com/48895485/99932236-6ea95b80-2d92-11eb-87cd-f48aee6a25be.png)

**Comment by ChrisZou** [comment]
感谢反馈，我看一下~

**Comment by ChrisZou** [comment]
已解决，应该是同一个session新发的博文删除的时候会出现。
